/*
 * Prototipo de um Sistema de controle de estoque em java
 */
package estoque;

import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.awt.event.WindowEvent;
import java.util.Arrays;
import javax.swing.JOptionPane;

/**
 *
 * @author Fabiano & Antônio
 */
public class FrmTelaLoginEstoque extends javax.swing.JFrame {

    /**
     * Creates new form TelaLoginEstoque
     */
    public FrmTelaLoginEstoque() {
        initComponents();
    }
    
    public static final String usuario = "User";
    public static final char[] senha = {'i','f','n','m','g'};
    
    public void closeFrame() 
    {// Método para fechar o frame.
        WindowEvent we = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(we);
    }
    
//    private void acionaLogin() {
//        if ((tfUsuario.getText().equals(usuario)) && (pfSenha.getPassword().equals(senha))) {
//            //JOptionPane.showMessageDialog(this, "Usuário e senha OK!!!", "Mensagem de confirmação", JOptionPane.ERROR_MESSAGE);
//            FrmTelaPrincipal fm = new FrmTelaPrincipal();
//            fm.setVisible(true);
//            //fm.recebeUsuario(tfUsuario.getText());
//            // Fechar a tela de login.
//            this.closeFrame();
//        } else {
//            JOptionPane.showMessageDialog(this, "Usuário e/ou senha incorretos!!!", "Erro de autenticação!", JOptionPane.ERROR_MESSAGE);
//        }
//    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnLogin = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        lblUsuario = new javax.swing.JLabel();
        tfUsuario = new javax.swing.JTextField();
        lblSenha = new javax.swing.JLabel();
        pfSenha = new javax.swing.JPasswordField();
        lblFundoLogin = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Entrar - SCE");
        setResizable(false);
        getContentPane().setLayout(null);

        btnLogin.setBackground(new java.awt.Color(0, 204, 0));
        btnLogin.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnLogin.setForeground(new java.awt.Color(255, 255, 255));
        btnLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Unlock-icon.png"))); // NOI18N
        btnLogin.setText("Login");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        getContentPane().add(btnLogin);
        btnLogin.setBounds(250, 220, 100, 33);

        btnCancelar.setBackground(new java.awt.Color(255, 51, 51));
        btnCancelar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnCancelar.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/close-icon.png"))); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancelar);
        btnCancelar.setBounds(390, 220, 120, 33);

        lblUsuario.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblUsuario.setForeground(new java.awt.Color(255, 255, 255));
        lblUsuario.setText("Usuario:");
        getContentPane().add(lblUsuario);
        lblUsuario.setBounds(170, 120, 70, 30);
        getContentPane().add(tfUsuario);
        tfUsuario.setBounds(250, 120, 260, 30);

        lblSenha.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblSenha.setForeground(new java.awt.Color(255, 255, 255));
        lblSenha.setText("Senha:");
        getContentPane().add(lblSenha);
        lblSenha.setBounds(170, 160, 70, 30);

        pfSenha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                pfSenhaKeyPressed(evt);
            }
        });
        getContentPane().add(pfSenha);
        pfSenha.setBounds(250, 160, 260, 30);

        lblFundoLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/88247.jpg"))); // NOI18N
        lblFundoLogin.setText("jLabel1");
        getContentPane().add(lblFundoLogin);
        lblFundoLogin.setBounds(0, 0, 599, 422);

        setSize(new java.awt.Dimension(615, 461));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        if(tfUsuario.getText().isEmpty() || pfSenha.getPassword().length == 0)
        {
            JOptionPane.showMessageDialog(this, "Não pode deixar algum campo em branco", "Alerta", 2);
        }
        else
        {
            if (tfUsuario.getText().equals(usuario) && Arrays.equals(pfSenha.getPassword(), senha))
            {
                FrmTelaPrincipal principal = new FrmTelaPrincipal();
                principal.setVisible(true);
                dispose();
            }
            else
            {
                JOptionPane.showMessageDialog(this, "Usuario ou Senha Incorretos", "Alerta", 2);
            }
        }
        
    }//GEN-LAST:event_btnLoginActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.closeFrame();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void pfSenhaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pfSenhaKeyPressed
        if (tfUsuario.getText().isEmpty()) 
        {
            JOptionPane.showMessageDialog(this, "Favor informar o usuário!", "Erro!", JOptionPane.ERROR_MESSAGE);
            pfSenha.setText("");
            pfSenha.setFocusable(false);
            tfUsuario.setFocusable(true);
            pfSenha.setFocusable(true);
        } else 
        {
            if (evt.getKeyCode() == KeyEvent.VK_ENTER) 
            {
                if (tfUsuario.getText().equals(usuario) && Arrays.equals(pfSenha.getPassword(), senha))
                {
                    FrmTelaPrincipal principal = new FrmTelaPrincipal();
                    principal.setVisible(true);
                    dispose();
                }
                else
                {
                    JOptionPane.showMessageDialog(this, "Usuario ou Senha Incorretos", "Alerta", 2);
                }
            }
        }
    }//GEN-LAST:event_pfSenhaKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmTelaLoginEstoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmTelaLoginEstoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmTelaLoginEstoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmTelaLoginEstoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmTelaLoginEstoque().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnLogin;
    private javax.swing.JLabel lblFundoLogin;
    private javax.swing.JLabel lblSenha;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JPasswordField pfSenha;
    private javax.swing.JTextField tfUsuario;
    // End of variables declaration//GEN-END:variables
}
